config/routes.rb
Rails.application.routes.draw do

  resources :crawlers do
    collection do
      get 'report'
      post 'click'
      post 'purchase'
    end
  end

  resources :brokers
  resources :quotes
  devise_for :users, :controllers => { :confirmations => 'confirmations', :registrations => 'registrations' }

  devise_scope :user do
    root to: "home#dashboard"
    patch "/confirm" => "confirmations#confirm"
  end

  resources :coefficients do
    collection do
      get 'select'
      post 'select'
      get 'filter'
      post 'filter'
      get 'import'
      post 'import'
      post 'update_async'
    end
  end

  resources :users

  resources :surveys do
    collection do
      get 'select'
      post 'select'
      get 'filter'
      post 'filter'
      get 'import'
      post 'import'
    end
  end

  resources :product_templates do
    collection do
      get 'build'
      post 'build'
      get 'save'
      post 'save'
    end
  end

  resources :products do
    collection do
      get 'grid'
      post 'add_multiple'
    end
  end

  resources :utilities
  resources :codings
  resources :insurers

  get 'dashboard' => 'home#dashboard'

  resources :insurers do
    collection do
      get '/:id/billing', to: 'insurers#billing', as: 'billing'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :home do
    collection do
      post 'update_graph'
      post 'dashboard'
      post 'grid'
    end
  end

  resources :tariffs do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]

      post 'export'
    end
  end

  resources :risks do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]
    end
  end

  resources :competitors do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]

      get 'grid'
      post 'update_graph'
    end
  end

  resources :lists do
    collection do
      get 'users'
      get 'datatables'
      get 'products'
    end
  end

  resources :reports do
    collection do
      get 'orders'
      get 'sales'
    end
  end

  resources :forms do
    collection do
      get 'new_customer'
      get 'new_product'
      get 'wizard'
    end
  end

  resources :pages do
    collection do
      get 'inbox'
      get 'profile'
      get 'latest_activity'
      get 'projects'
      get 'steps'
      get 'calendar'
    end
  end

  resources :pricing do
    collection do
      get 'plans'
      get 'charts'
      get 'form'
      get 'invoice'
    end
  end

  resources :features do
    collection do
      get 'email_templates'
      get 'gallery'
      get 'ui'
      get 'api'
      get 'signup'
      get 'signin'
      get 'status'
    end
  end

  resources :account do
    collection do
      get 'settings'
      get 'billing'
      get 'notifications'
      get 'support'
    end
  end
end

app/models/coefficient.rb
class Coefficient < ActiveRecord::Base
  store_accessor :intercept
  #after_initialize :add_field_accessors
  #serialize :coefficients, HashSerializer
  store_accessor :coefficients

  def self.truncate_me!
    Coefficient.connection.execute("TRUNCATE TABLE coefficients RESTART IDENTITY")
  end

  def add_store_accessor field_name
      singleton_class.class_eval {store_accessor :coefficients, field_name}
  end

  def add_field_accessors
    num_fields = coefficients.try(:keys).try(:count) || 0
    coefficients.keys.each {|field_name| add_store_accessor field_name} if num_fields > 0
  end

  def self.import(file, filters)

    file = File.new("#{Rails.root}/tmp/files/#{file}", "r")

    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.sheet(0).row(1)

    Coefficient.truncate_me!

    (2..spreadsheet.last_row).each do |i|

      row2 = Hash[[header, spreadsheet.row(i)].transpose]
      intercept = row2["CONSTANT"].to_f

      row = row2.except!("CONSTANT")
      row.update(row){ |k,v| v.to_f }

      Coefficient.create!(:intercept => intercept, :coefficients => row, :product_template_id => 1)
    end

    avg_intercept = sprintf("%.5f", Coefficient.average(:intercept))
    avg_price = sprintf("%.5f", Coefficient.connection.execute("SELECT round(AVG((coefficients->>'Price_L')::numeric),5) FROM coefficients").first["round"])

    competitors = Competitor.select(:id, :premium).group(:id, :insurer)

    # Procurar por competitor id para encontrar
    #Product.all.each do |product|
    #  utility = avg_intercept + avg_price * competitor.premium
    #  product.update_attributes(:utility => utility, :logit_e => Math.exp(utility.to_f))
    #end
  end

  protected

    def self.friendly
      @friendly ||= columns.map { |column| column.name }
      @friendly.except(["id", "created_at","updated_at","product_template_id"])
    end

    def self.open_spreadsheet(file)
      case File.extname(file.path)
        when ".csv" then Roo::CSV.new(file.path)
        when ".xls" then Roo::Excel.new(file.path)
        when ".xlsx" then Roo::Excelx.new(file.path)
        else raise "Unknown file type: #{file.path}"
      end
    end

  private
end

app/controllers/coefficients_controller.rb
class CoefficientsController < ApplicationController
  before_action :set_coefficient, only: [:show, :edit, :update, :destroy]

  # GET /coefficients
  # GET /coefficients.json
  def index
    @coefficients = Coefficient.all
  end

  # GET /coefficients/1
  # GET /coefficients/1.json
  def show
  end

  # GET /coefficients/new
  def new
    @coefficient = Coefficient.new
  end

  # GET /coefficients/select
  def select

    ## Save file to tmp/files/
    @name = "#{Time.now.strftime("%Y%m%d%H%M%S")}_#{params[:file].original_filename}"
    directory = "tmp/files"
    path = File.join(directory, @name)
    File.open(path, "wb") { |f| f.write(params[:file].read) }

    file = File.open(path, 'r')

    spreadsheet = Coefficient.open_spreadsheet(file)
    @header = spreadsheet.sheet(0).row(1)
  end

  # GET /coefficients/import
  def import

    file    = params[:file]
    filters = params[:filters]

    Coefficient.import(file, filters)
  end

  def update_async

    @keys = Coefficient.first.coefficients.keys

    @competitors = Competitor.all

    data = []
    @competitors.each do |p|
      temp = Competitor.new(name: p[:name],   premium: p[:premium], tariff_id: p[:tariff_id])
      data << temp
    end

    g = PivotTable::Grid.new do |g|
      g.source_data  = data
      g.column_name  = :name
      g.row_name     = :tariff_id
      g.field_name   = :premium
    end

    @pivot = g.build

    # Handle POST requests
    tariff = params[:tariff]
    @value = params[:value]
    insurer = params[:insurer]

    competitor = Competitor.find_by(name: insurer, tariff_id: tariff)
    competitor.premium = @value
    competitor.save

    respond_to do |format|
      format.js
    end
  end

  # GET /coefficients/1/edit
  def edit
  end

  # POST /coefficients
  # POST /coefficients.json
  def create
    @coefficient = Coefficient.new(coefficient_params)

    respond_to do |format|
      if @coefficient.save
        format.html { redirect_to @coefficient, notice: 'Coefficient was successfully created.' }
        format.json { render :show, status: :created, location: @coefficient }
      else
        format.html { render :new }
        format.json { render json: @coefficient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coefficients/1
  # PATCH/PUT /coefficients/1.json
  def update
    respond_to do |format|
      if @coefficient.update(coefficient_params)
        format.html { redirect_to @coefficient, notice: 'Coefficient was successfully updated.' }
        format.json { render :show, status: :ok, location: @coefficient }
      else
        format.html { render :edit }
        format.json { render json: @coefficient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coefficients/1
  # DELETE /coefficients/1.json
  def destroy
    @coefficient.destroy
    respond_to do |format|
      format.html { redirect_to coefficients_url, notice: 'Coefficient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coefficient
      @coefficient = Coefficient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coefficient_params
      params[:coefficient]
    end

    # Open imported spreadsheet
    def open_spreadsheet(file)
      case File.extname(file.original_filename)
        when ".csv" then Roo::CSV.new(file.path)
        when ".xls" then Roo::Excel.new(file.path)
        when ".xlsx" then Roo::Excelx.new(file.path)
        else raise "Unknown file type: #{file.original_filename}"
      end
    end
end

app/helpers/coefficients_helper.rb
module CoefficientsHelper
end

app/views/coefficients/_chart.html.slim
div class="chart"
  div class="bar-chart-wrapper"
     div id="bar-chart"

app/views/coefficients/_form.html.erb
<%= form_for(@coefficient) do |f| %>
  <% if @coefficient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coefficient.errors.count, "error") %> prohibited this coefficient from being saved:</h2>

      <ul>
      <% @coefficient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coefficients/_utilities.html.erb
<%= debug @value %>
  <thead>
    <tr>
      <th tabindex="0" rowspan="1" colspan="1">Intercept</th>
      <% @keys.each do |k| %>
        <th tabindex="0" rowspan="1" colspan="1"><%= k %></th>
      <% end %>
      <th tabindex="0" rowspan="1" colspan="1">U(A)</th>
      <th tabindex="0" rowspan="1" colspan="1">U(B)</th>
      <th tabindex="0" rowspan="1" colspan="1">U(C)</th>
      <th tabindex="0" rowspan="1" colspan="1">U(D)</th>
      <th tabindex="0" rowspan="1" colspan="1">U(E)</th>
      <th tabindex="0" rowspan="1" colspan="1">Máx Util</th>
      <th tabindex="0" rowspan="1" colspan="1">Logit</th>
      <th tabindex="0" rowspan="1" colspan="1">Logit(%)</th>
    </tr>
  </thead>

  <tbody>
    <% Coefficient.all.each do |c| %>
    <tr>
      <td><%= c.intercept %></td>
      <% @keys.each do |k| %>
        <td><%= c.coefficients[k] %></td>
      <% end %>
      <% @pivot.rows.first.data.each do |d| %>
        <td><%= d  %></td>
        <!--<td><%# (c.intercept + d * c.coefficients["Preco_L"]).round(1) %></td>
        <td><%# (c.intercept + d * c.coefficients["Preco_L"]).round(1) %></td>
        <td><%# (c.intercept + d * c.coefficients["Preco_L"]).round(1) %></td>
        <td><%# (c.intercept + d * c.coefficients["Preco_L"]).round(1) %></td>
        <td><%# (c.intercept + d * c.coefficients["Preco_L"]).round(1) %></td>-->
      <% end %>
    </tr>
    <% end %>
  </tbody>

app/views/coefficients/edit.html.erb
<h1>Editing Coefficient</h1>

<%= render 'form' %>

<%= link_to 'Show', @coefficient %> |
<%= link_to 'Back', coefficients_path %>

app/views/coefficients/import.html.slim
  - provide :title, "Experimental Design"
  = content_for :body_id, "wizard-third"
  == render :partial => "shared/wizard_steps"

  section class="form-wizard"
    div class="step active animated fadeInRightStep"
      div class="success"
        i class="ion-checkmark-circled"
        h3
          | Beta coefficients were uploaded successfully!

        a href= coefficients_path class="button"
          span View beta coefficients

app/views/coefficients/index.html.slim
  - provide :title, "Experimental Design"
  = content_for :body_id, "coefficients"

  div class="menubar"
    div class="sidebar-toggler visible-xs"
      i class="ion-navicon"

    div class="page-title"
      | Beta coefficients
    div class="options pull-right hidden-xs"
      a href="#"
        i class="fa fa-download"
        | Download CSV

  div class="content-wrapper"

    div class="results"

      div class="top-bar"

      div class="middle-bar"
        table id="coefficients-datatable" class="table"
          thead
            tr
              - unless Coefficient.all.empty?
                th ID
                th Intercept
                - Coefficient.first.coefficients.keys.each do |coefficient|
                  th
                    = coefficient

          tbody
            - unless Coefficient.all.empty?
              - @coefficients.each do |coefficient|
                tr
                  td
                    = coefficient.id
                  td
                    = best_in_place coefficient, :intercept
                  - unless coefficient.coefficients.blank?
                    - coefficient.coefficients.each do |key,value|
                      td
                        = value
                        /best_in_place coefficient, key > corrigir para permitir best_in_place mas também SELECT queries

      div class="bottom-bar"

app/views/coefficients/new.html.slim
  - provide :title, "Experimental Design"
  = content_for :body_id, "wizard-first"
  == render "shared/wizard_steps"

  section class="form-wizard"

    div class="step active animated fadeInRightStep"

      = label_tag :file do
        = image_tag "file-upload.png"

      = form_tag select_coefficients_path, multipart: true do
        div class="form-group"
          = label "file", nil, class: "form-control"
          = file_field_tag :file

        == render :partial => "shared/buttons_footer"

app/views/coefficients/select.html.slim
  - provide :title, "Experimental Design"
  = content_for :body_id, "wizard-second"
  == render "shared/wizard_steps"

  section class="form-wizard"

    div class="instructions"
      strong
        | Please choose below &nbsp;
      | which properties do you want to include:

    div class="step active animated fadeInRightStep"
    = form_tag import_coefficients_path do
      = hidden_field_tag "file", @name
      div class="plans"
        - unless @header.blank?
          - @header.each_with_index do |header, i|
            - unless header == "Premio comercial"
              div class="plan clearfix selected"
                div class="info"
                  div class="name"
                    = header
                  div class="select"
                    = hidden_field_tag "filters[]", @header[i]
                    i class="fa fa-check"

      == render "shared/buttons_footer"

app/views/coefficients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_coefficient_path(@coefficient) %> |
<%= link_to 'Back', coefficients_path %>

app/views/coefficients/simulation.html.erb
<% provide(:title, "Experimental Design") %>
<%= content_for :body_id, "datatables" %>

<script>
$(document).ready ( function () {

  $("#orders-datatable-2 > tbody > tr input").on("keyup", function(event) {
    event.preventDefault();

    var $th = $("#orders-datatable-2 thead tr th").eq($(this).parent().parent().index());

    var insurer = $th.text();
    var tariff = $(this).attr("name");
    var value = $(this).val();

    $.ajax({
      type: "POST",
      url: "/coefficients/update_async",
      cache: false,
      async: true,
      data: {
        tariff: tariff,
        value: value,
        insurer: insurer
      },
      success: function(result) {
        // Append the result to a table or list, $("list").append(result)
      }
    });
  });

});
</script>

<div class="menubar">
  <div class="sidebar-toggler visible-xs">
    <i class="ion-navicon"></i>
  </div>

  <div class="page-title">
    Simulator
  </div>
</div>

<div class="content-wrapper" style="overflow:auto !important">
<%# render :partial => "shared/filter_table" %>

  <table id="orders-datatable-2" style="margin:0 auto">
    <thead>
      <tr>
        <th tabindex="0" rowspan="1" colspan="1">Tariff</th>
        <% @pivot.column_headers.each do |c| %>
          <th tabindex="0" rowspan="1" colspan="1"><%= c %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% unless @competitors.empty? %>
        <% @pivot.rows.each do |r| %>
          <tr>
            <td><a href="<%= tariff_path(r.header) %>"><%= r.header %></a></td>
            <% r.data.each do |d| %>
              <td>
              <div class="has-feedback">
                <%= text_field_tag r.header, d, :class => "form-control" %>
                <i class="ion-reply form-control-feedback" style="margin-top:-25px; cursor:pointer" data-toggle="tooltip" title="Reverse changes">
                </i>
                </div>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>

    </table>

  <div style="height:50px"></div>

  <table id="orders-datatable">
    <%= render "coefficients/utilities" %>
  </table>

</div>

app/views/coefficients/update_async.js.erb
$("#orders-datatable").html("<%= escape_javascript(render(:partial => 'coefficients/utilities')).html_safe %>");