config/routes.rb
Rails.application.routes.draw do

  resources :crawlers do
    collection do
      get 'report'
      post 'click'
      post 'purchase'
    end
  end

  resources :brokers
  resources :quotes
  devise_for :users, :controllers => { :confirmations => 'confirmations', :registrations => 'registrations' }

  devise_scope :user do
    root to: "home#dashboard"
    patch "/confirm" => "confirmations#confirm"
  end

  resources :coefficients do
    collection do
      get 'select'
      post 'select'
      get 'filter'
      post 'filter'
      get 'import'
      post 'import'
      post 'update_async'
    end
  end

  resources :users

  resources :surveys do
    collection do
      get 'select'
      post 'select'
      get 'filter'
      post 'filter'
      get 'import'
      post 'import'
    end
  end

  resources :product_templates do
    collection do
      get 'build'
      post 'build'
      get 'save'
      post 'save'
    end
  end

  resources :products do
    collection do
      get 'grid'
      post 'add_multiple'
    end
  end

  resources :utilities
  resources :codings
  resources :insurers

  get 'dashboard' => 'home#dashboard'

  resources :insurers do
    collection do
      get '/:id/billing', to: 'insurers#billing', as: 'billing'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :home do
    collection do
      post 'update_graph'
      post 'dashboard'
      post 'grid'
    end
  end

  resources :tariffs do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]

      post 'export'
    end
  end

  resources :risks do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]
    end
  end

  resources :competitors do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]

      get 'grid'
      post 'update_graph'
    end
  end

  resources :lists do
    collection do
      get 'users'
      get 'datatables'
      get 'products'
    end
  end

  resources :reports do
    collection do
      get 'orders'
      get 'sales'
    end
  end

  resources :forms do
    collection do
      get 'new_customer'
      get 'new_product'
      get 'wizard'
    end
  end

  resources :pages do
    collection do
      get 'inbox'
      get 'profile'
      get 'latest_activity'
      get 'projects'
      get 'steps'
      get 'calendar'
    end
  end

  resources :pricing do
    collection do
      get 'plans'
      get 'charts'
      get 'form'
      get 'invoice'
    end
  end

  resources :features do
    collection do
      get 'email_templates'
      get 'gallery'
      get 'ui'
      get 'api'
      get 'signup'
      get 'signin'
      get 'status'
    end
  end

  resources :account do
    collection do
      get 'settings'
      get 'billing'
      get 'notifications'
      get 'support'
    end
  end
end

app/models/insurer.rb
class Insurer < ActiveRecord::Base
  has_many :users
  has_many :tariffs
end

app/controllers/insurers_controller.rb
class InsurersController < ApplicationController
  before_action :set_insurer, only: [:show, :edit, :update, :destroy]

  # GET /insurers
  # GET /insurers.json
  def index
    @insurers = Insurer.all
  end

  # GET /insurers/1
  # GET /insurers/1.json
  def show
  end

  # GET /insurers/new
  def new
    @insurer = Insurer.new
  end

  # GET /insurers/1/edit
  def edit
    @insurer = Insurer.find_by_id(1)
  end

  def billing
    @tariff = Tariff.find(1)
  end

  # POST /insurers
  # POST /insurers.json
  def create
    @insurer = Insurer.new(insurer_params)

    respond_to do |format|
      if @insurer.save
        format.html { redirect_to @insurer, notice: 'Insurer was successfully created.' }
        format.json { render :show, status: :created, location: @insurer }
      else
        format.html { render :new }
        format.json { render json: @insurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /insurers/1
  # PATCH/PUT /insurers/1.json
  def update
    respond_to do |format|
      if @insurer.update(insurer_params)
        format.html { redirect_to @insurer, notice: 'Insurer was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurer }
      else
        format.html { render :edit }
        format.json { render json: @insurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /insurers/1
  # DELETE /insurers/1.json
  def destroy
    @insurer.destroy
    respond_to do |format|
      format.html { redirect_to insurers_url, notice: 'Insurer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurer
      @insurer = Insurer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def insurer_params
      params[:insurer]
    end
end

app/helpers/insurers_helper.rb
module InsurersHelper
end

app/views/insurers/_form.html.erb
<%= form_for(@insurer) do |f| %>
  <% if @insurer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@insurer.errors.count, "error") %> prohibited this insurer from being saved:</h2>

      <ul>
      <% @insurer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/insurers/billing.html.erb
<%= content_for :body_id, "account" %>

<div id="sidebar">
  <div class="sidebar-toggler visible-xs">
    <i class="ion-navicon"></i>
  </div>

  <h3>My company</h3>
  <ul class="menu">
    <li>
      <a href="<%= insurer_path(1) %>" class="active">
        <i class="ion-ios-briefcase-outline"></i>
        Profile
      </a>
    </li>
    <li>
      <a href="<%= billing_insurers_path(1) %>" class="active">
        <i class="ion-card"></i>
        Billing
      </a>
    </li>
  </ul>
</div>

<div id="panel" class="profile">
  <div class="billing">
    <div class="secure clearfix">
      <span class="lock pull-left">
        <i class="fa fa-lock"></i>
        Secure Billing Form
      </span>
      <div class="accepted-cards pull-right">
        <%= image_tag "credit_card_types.gif" %>
      </div>
    </div>

    <form id="billing" class="form-horizontal" method="post" action="#" role="form">
        <div class="form-group">
          <label class="col-sm-3 control-label">Name on Card</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" placeholder="Your full name" name="customer[first_name]" />
          </div>
        </div>
        <div class="address">
          <div class="form-group">
            <label class="col-sm-3 control-label">Address</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" placeholder="Address" name="customer[address]" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-5 col-sm-offset-3">
                <input type="text" class="form-control mobile-margin-bottom" placeholder="City" name="customer[city]" />
            </div>
            <div class="col-sm-4">
                <input type="text" class="form-control" placeholder="Zip/Postal" name="customer[state]" />
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-5 col-sm-offset-3">
                <input type="text" class="form-control mobile-margin-bottom" placeholder="Country" name="customer[city]" />
            </div>
            <div class="col-sm-4">
                <input type="text" class="form-control" placeholder="State" name="customer[state]" />
            </div>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Card Number</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" placeholder="••••  ••••  ••••  ••••" name="customer[first_name]" />
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Expiration & CVC</label>
          <div class="col-sm-5">
              <input type="text" class="form-control mobile-margin-bottom" placeholder="MM/YYY" name="customer[city]" />
          </div>
          <div class="col-sm-4">
              <input type="text" class="form-control" placeholder="CVC" name="customer[state]" />
          </div>
        </div>

        <div class="instructions">
          Your credit card will be charged for the monthly <strong>Business plan of $59.00 USD</strong> on April 12, 2016. This will cover your subscription from: April 12, 2015 to May 12, 2016.
        </div>

        <div class="action clearfix">
        <a href="#" class="btn btn-success">
          Make payment
          <i class="fa fa-chevron-right"></i>
        </a>
      </div>
    </form>
  </div>
</div>

app/views/insurers/edit.html.erb
<%= content_for :body_id, "account" %>

<div id="sidebar">
  <div class="sidebar-toggler visible-xs">
    <i class="ion-navicon"></i>
  </div>

  <h3>My company</h3>
  <ul class="menu">
    <li>
      <a href="<%= insurer_path(1) %>" class="active">
        <i class="ion-briefcase" style="font-size:20px"></i> <!-- ion-ios7-cog-outline -->
        Profile
      </a>
    </li>
    <li>
      <a href="<%= billing_insurers_path(1) %>" class="active">
        <i class="ion-card"></i>
        Billing
      </a>
    </li>
  </ul>
</div>

<div id="panel" class="profile">
  <h3>
    Profile settings
  </h3>

  <p class="intro">
    Change your company's profile, logo, billing information, etc.
  </p>

  <%= form_for(@insurer, multipart: true) do |i| %>
    <div class="form-group avatar-field clearfix">
        <div class="col-sm-3">
          <%= image_tag "avatars/company.png", class: "img-responsive img-circle" %>
        </div>
        <div class="col-sm-9">
          <label>Set up your company's logo</label>
            <%# f.file_field :avatar %>
        </div>
      </div>
      <div class="form-group">
      <%= i.label :name %>
      <%= i.text_field :name, :class => "form-control", :placeholder => "My company's name" %>
    </div>
    <div class="form-group">
      <%= i.label :address %>
      <%= i.text_field :address, class: "form-control", :placeholder => "My company's address" %>
    </div>
    <div class="form-group">
      <%= i.label :city %>
      <%= i.text_field :city, class: "form-control", :placeholder => "My company's HQ location" %>
    </div>
    <div class="form-group">
      <%= i.label :zip %>
      <%= i.text_field :zip, class: "form-control", :placeholder => "My company's zip code" %>
    </div>
    <div class="form-group action">
      <input type="submit" class="btn btn-success" value="Save changes" />
    </div>
  <% end %>
</div>

app/views/insurers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Insurers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @insurers.each do |insurer| %>
      <tr>
        <td><%= link_to 'Show', insurer %></td>
        <td><%= link_to 'Edit', edit_insurer_path(insurer) %></td>
        <td><%= link_to 'Destroy', insurer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Insurer', new_insurer_path %>

app/views/insurers/new.html.erb
<h1>New Insurer</h1>

<%= render 'form' %>

<%= link_to 'Back', insurers_path %>

app/views/insurers/show.html.erb
<%= content_for :body_id, "account" %>

<div id="sidebar">
  <div class="sidebar-toggler visible-xs">
    <i class="ion-navicon"></i>
  </div>

  <h3>My company</h3>
  <ul class="menu">
    <li>
      <a href="<%= insurer_path(1) %>" class="active">
        <i class="ion-ios-briefcase-outline"></i>
        Profile
      </a>
    </li>
    <li>
      <a href="<%= billing_insurers_path(1) %>" class="active">
        <i class="ion-card"></i>
        Billing
      </a>
    </li>
  </ul>
</div>

<div id="panel" class="profile">
  <h3>
    Profile settings
  </h3>

  <p class="intro">
    Change your company's profile, logo, billing information, etc.
  </p>

  <%= form_for(@insurer, multipart: true) do |i| %>
    <div class="form-group avatar-field clearfix">
        <div class="col-sm-3">
          <%= image_tag "avatars/company.png", class: "img-responsive img-circle" %>
        </div>
        <div class="col-sm-9">
          <label>Set up your company's logo</label>
            <%# f.file_field :avatar %>
        </div>
      </div>
      <div class="form-group">
      <%= i.label :name %>
      <%= i.text_field :name, :class => "form-control", :placeholder => "My company's name" %>
    </div>
    <div class="form-group">
      <%= i.label :address %>
      <%= i.text_field :address, class: "form-control", :placeholder => "My company's address" %>
    </div>
    <div class="form-group">
      <%= i.label :city %>
      <%= i.text_field :city, class: "form-control", :placeholder => "My company's HQ location" %>
    </div>
    <div class="form-group">
      <%= i.label :zip %>
      <%= i.text_field :zip, class: "form-control", :placeholder => "My company's zip code" %>
    </div>
    <div class="form-group action">
      <input type="submit" class="btn btn-success" value="Save changes" />
    </div>
  <% end %>
</div>