config/routes.rb
Rails.application.routes.draw do

  resources :crawlers do
    collection do
      get 'report'
      post 'click'
      post 'purchase'
    end
  end

  resources :brokers
  resources :quotes
  devise_for :users, :controllers => { :confirmations => 'confirmations', :registrations => 'registrations' }

  devise_scope :user do
    root to: "home#dashboard"
    patch "/confirm" => "confirmations#confirm"
  end

  resources :coefficients do
    collection do
      get 'select'
      post 'select'
      get 'filter'
      post 'filter'
      get 'import'
      post 'import'
      post 'update_async'
    end
  end

  resources :users

  resources :surveys do
    collection do
      get 'select'
      post 'select'
      get 'filter'
      post 'filter'
      get 'import'
      post 'import'
    end
  end

  resources :product_templates do
    collection do
      get 'build'
      post 'build'
      get 'save'
      post 'save'
    end
  end

  resources :products do
    collection do
      get 'grid'
      post 'add_multiple'
    end
  end

  resources :utilities
  resources :codings
  resources :insurers

  get 'dashboard' => 'home#dashboard'

  resources :insurers do
    collection do
      get '/:id/billing', to: 'insurers#billing', as: 'billing'
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :home do
    collection do
      post 'update_graph'
      post 'dashboard'
      post 'grid'
    end
  end

  resources :tariffs do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]

      post 'export'
    end
  end

  resources :risks do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]
    end
  end

  resources :competitors do
    collection do
      match 'select', via: [:get, :post]
      match 'map', via: [:get, :post]
      match 'import', via: [:get, :post]

      get 'grid'
      post 'update_graph'
    end
  end

  resources :lists do
    collection do
      get 'users'
      get 'datatables'
      get 'products'
    end
  end

  resources :reports do
    collection do
      get 'orders'
      get 'sales'
    end
  end

  resources :forms do
    collection do
      get 'new_customer'
      get 'new_product'
      get 'wizard'
    end
  end

  resources :pages do
    collection do
      get 'inbox'
      get 'profile'
      get 'latest_activity'
      get 'projects'
      get 'steps'
      get 'calendar'
    end
  end

  resources :pricing do
    collection do
      get 'plans'
      get 'charts'
      get 'form'
      get 'invoice'
    end
  end

  resources :features do
    collection do
      get 'email_templates'
      get 'gallery'
      get 'ui'
      get 'api'
      get 'signup'
      get 'signin'
      get 'status'
    end
  end

  resources :account do
    collection do
      get 'settings'
      get 'billing'
      get 'notifications'
      get 'support'
    end
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base

  def self.truncate_me!
    Survey.connection.execute("TRUNCATE TABLE surveys RESTART IDENTITY")
  end

  def self.import(file, filters)

    file = File.new("#{Rails.root}/tmp/files/#{file}", "r")

    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.sheet(0).row(1)

    Survey.truncate_me!

    for i in 1..header.length
      temp = spreadsheet.sheet(0).column(i)
      temp.tap do |head, *body|
        body.each do |b|
          Survey.create!(:product => head, :answer => b.to_i)
        end
      end
    end
  end

  protected

    def self.friendly
      @friendly ||= columns.map { |column| column.name }
      @friendly.except(["created_at","updated_at","product_id"])
    end

    def self.open_spreadsheet(file)
      case File.extname(file.path)
        when ".csv" then Roo::CSV.new(file.path, csv_options: {col_sep: ";"})
        when ".xls" then Roo::Excel.new(file.path)
        when ".xlsx" then Roo::Excelx.new(file.path)
        else raise "Unknown file type: #{file.path}"
      end
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    survey_bars = []
    surveys = []

    results = Survey.select(:product, "SUM(answer)").group(:product).order(:product)

    results.each_with_index do |r, index|
      survey_bars << [r.product, r.sum]
      surveys <<  [index, r.product]
    end

    gon.survey_bars = survey_bars
    gon.surveys = surveys
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/select
  def select

    ## Save file to tmp/files/
    @name = "#{Time.now.strftime("%Y%m%d%H%M%S")}_#{params[:file].original_filename}"
    directory = "tmp/files"
    path = File.join(directory, @name)
    File.open(path, "wb") { |f| f.write(params[:file].read) }

    file = File.open(path, 'r')

    spreadsheet = Survey.open_spreadsheet(file)
    @header = spreadsheet.sheet(0).row(1)
  end

  # GET /tariffs/import
  def import

    file    = params[:file]
    filters = params[:filters]

    Survey.import(file, filters)
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params[:survey]
    end

    # Open imported spreadsheet
    def open_spreadsheet(file)
      case File.extname(file.original_filename)
        when ".csv" then Roo::CSV.new(file.path, csv_options: {col_sep: ";"})
        when ".xls" then Roo::Excel.new(file.path)
        when ".xlsx" then Roo::Excelx.new(file.path)
        else raise "Unknown file type: #{file.original_filename}"
      end
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_chart.html.slim
div class="chart"
  div class="bar-chart-wrapper"
     div id="bar-chart"

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/import.html.slim
- provide :title, "Customer Analysis"
= content_for :body_id, "wizard-third"
== render :partial => "shared/wizard_steps"

section class="form-wizard"
  div class="step active animated fadeInRightStep"
    div class="success"
      i class="ion-checkmark-circled"
      h3
        | Survey results were uploaded successfully!

      a href= surveys_path class="button"
        span View survey results table

app/views/surveys/index.html.slim
  - provide :title, "Customer Analysis"
  = content_for :body_id, "surveys"

  div class="menubar"
    div class="sidebar-toggler visible-xs"
      i class="ion-navicon"

    div class="page-title"
      | Survey results

  div class="content-wrapper"

    div class="results"

      == render "surveys/chart"

      div class="top-bar"

      div class="middle-bar"
        table id="surveys-datatable" class="table"
          thead
            tr
              - Survey.friendly.each do |c|
                th
                  = c.camelize

          tbody
            - @surveys.each do |survey|
              tr
                td
                  = survey.id
                td
                  = best_in_place survey, :product
                td
                  = best_in_place survey, :answer

      div class="bottom-bar"

app/views/surveys/new.html.slim
- provide :title, "Customer Analysis"
= content_for :body_id, "wizard-first"
== render "shared/wizard_steps"

section class="form-wizard"

  div class="step active animated fadeInRightStep"

    = label_tag :file do
      = image_tag "file-upload.png"

    = form_tag select_surveys_path, multipart: true do
      div class="form-group"
        = label "file", nil, class: "form-control"
        = file_field_tag :file

      == render :partial => "shared/buttons_footer"

app/views/surveys/select.html.slim
- provide :title, "Customer Analysis"
= content_for :body_id, "wizard-second"
== render "shared/wizard_steps"

section class="form-wizard"

  div class="instructions"
    strong
      | Please choose below &nbsp;
    | which properties do you want to include:

  div class="step active animated fadeInRightStep"
  = form_tag import_surveys_path do
    = hidden_field_tag "file", @name
    div class="plans"
      - unless @header.blank?
        - @header.each_with_index do |header, i|
          - unless header == "Premio comercial"
            div class="plan clearfix selected"
              div class="info"
                div class="name"
                  = header
                div class="select"
                  = hidden_field_tag "filters[]", @header[i]
                  i class="fa fa-check"

    == render "shared/buttons_footer"

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>